defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "resource"

  - scope:
      path: "db"
      type: "pages"
    values:
      layout: "db"

  - scope:
      path: "os"
      type: "pages"
    values:
      layout: "os"

  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
